project:
  type: book

book:
  title: "Reproducible Medical Research With R"
  author: "Peter Higgins"
  date: "1/27/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - wrangle.qmd
    - inset_table.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: true

filters:
  - webr
engine: knitr

format: live-html
webr:
  engine: knitr
  packages:
    - tidyverse
    - gt
    - medicaldata
